#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import io
import json
import re
import shutil
import zipfile
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
SYSTEM = ROOT / "content" / "pattern-system"
COL = SYSTEM / "collections" / "iconic-destinations"
ZIP_REL = "collections/iconic-destinations/assets/iconic-destinations-canonical-100.zip"
ZIP_PATH = SYSTEM / ZIP_REL
SOURCE_DIR = COL / "source-images"
SOURCE_MANIFEST = SOURCE_DIR / "manifest.json"
INPUT_DIR = COL / "input-pngs-q50" / "canonical-100"
DESIGNS_PATH = COL / "designs.json"
QUEUE_PATH = SYSTEM / "iconic_destinations" / "publish_queue.json"
PATTERNS = SYSTEM / "patterns"
PRODUCTS = SYSTEM / "products"
CATALOG_PATH = ROOT / "content" / "products" / "catalog.json"
APPROVED_DIR = COL / "approved-pixel-designs"
MAPPED_DIR = COL / "source-designs"

EXPECTED_IDS = [f"D{i:04d}" for i in range(1, 101)]
WIDTH, HEIGHT, COLOURS = 100, 120, 50


def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def validate_manifest(manifest: dict):
    if manifest.get("collection") != "iconic-destinations":
        raise SystemExit("Wrong collection in manifest")
    items = manifest.get("items") or []
    if len(items) != 100:
        raise SystemExit(f"Expected 100 manifest items, got {len(items)}")
    ids = [x.get("id") for x in items]
    if ids != EXPECTED_IDS:
        raise SystemExit(f"Manifest IDs must be sequential D0001-D0100: {ids[:3]} ... {ids[-3:]}")
    filenames = [x.get("filename") for x in items]
    slugs = [x.get("slug") for x in items]
    if len(set(filenames)) != 100 or len(set(slugs)) != 100:
        raise SystemExit("Manifest filenames/slugs must be unique")
    for i, item in enumerate(items, start=1):
        base = f"D{i:04d}"
        slug = str(item.get("slug") or "")
        expected_filename = f"{base}-{slug}.png"
        if item.get("filename") != expected_filename:
            raise SystemExit(f"{base}: filename must be {expected_filename}")
        for key in ("title_en", "title_es", "product_title_en", "product_title_es"):
            if not str(item.get(key) or "").strip():
                raise SystemExit(f"{base}: missing {key}")
        if item.get("width") != WIDTH or item.get("height") != HEIGHT:
            raise SystemExit(f"{base}: manifest dimensions are wrong")
        if item.get("color_count") != COLOURS:
            raise SystemExit(f"{base}: manifest color_count must be 50")
        if item.get("palette_mode") != "independent_per_image":
            raise SystemExit(f"{base}: palette must be independent per image")
    return items


if not ZIP_PATH.is_file():
    raise SystemExit(f"Missing canonical ZIP: {ZIP_PATH}")

with zipfile.ZipFile(ZIP_PATH, "r") as zf:
    if "manifest.json" not in zf.namelist():
        raise SystemExit("Canonical ZIP is missing manifest.json")
    manifest = json.loads(zf.read("manifest.json").decode("utf-8"))
    items = validate_manifest(manifest)

    expected_pngs = [x["filename"] for x in items]
    actual_pngs = sorted(n for n in zf.namelist() if n.lower().endswith(".png"))
    if actual_pngs != sorted(expected_pngs):
        raise SystemExit("ZIP PNG set does not match manifest")

    # Canonical collection source structure. Remove stale sources so there is
    # only one authoritative image for each current design.
    if SOURCE_DIR.exists():
        shutil.rmtree(SOURCE_DIR)
    SOURCE_DIR.mkdir(parents=True, exist_ok=True)
    if (COL / "input-pngs-q50").exists():
        shutil.rmtree(COL / "input-pngs-q50")
    INPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Derived folders are regenerated by the publisher. Remove historical
    # images so old IDs/slugs cannot be mistaken for current sources.
    for derived in (APPROVED_DIR, MAPPED_DIR):
        if derived.exists():
            shutil.rmtree(derived)
        derived.mkdir(parents=True, exist_ok=True)

    for item in items:
        raw = zf.read(item["filename"])
        with Image.open(io.BytesIO(raw)) as im:
            rgb = im.convert("RGB")
            colours = len(rgb.getcolors(maxcolors=1000000))
            if im.format != "PNG" or rgb.size != (WIDTH, HEIGHT) or colours != COLOURS:
                raise SystemExit(
                    f"{item['id']}: format={im.format} size={rgb.size} colours={colours}"
                )
        digest = hashlib.sha256(raw).hexdigest()
        if item.get("source_sha256") and item["source_sha256"] != digest:
            raise SystemExit(f"{item['id']}: SHA-256 mismatch")
        (SOURCE_DIR / item["filename"]).write_bytes(raw)
        (INPUT_DIR / item["filename"]).write_bytes(raw)

    # Persist the exact metadata source used to build product records.
    write_json(SOURCE_MANIFEST, manifest)

# Rebuild the collection design manifest strictly from source-images/manifest.json.
design_rows = []
queue_rows = []
for order, item in enumerate(items, start=1):
    base = item["id"]
    filename = item["filename"]
    input_rel = f"collections/iconic-destinations/input-pngs-q50/canonical-100/{filename}"
    source_rel = f"collections/iconic-destinations/source-images/{filename}"
    common = {
        "base_design_id": base,
        "title_en": item["title_en"],
        "title_es": item["title_es"],
        "slug": item["slug"],
        "input_png": input_rel,
        "source_zip": ZIP_REL,
        "source_zip_member": filename,
        "source_manifest": "collections/iconic-destinations/source-images/manifest.json",
        "source_image": source_rel,
    }
    design_rows.append({
        "order": order,
        **common,
        "product_title_en": item["product_title_en"],
        "product_title_es": item["product_title_es"],
        "variants": [f"{base}-CS"],
        "artwork_status": "approved-manifest-individual-png-100x120",
        "source_asset": input_rel,
        "palette_mode": "per-design",
        "palette_status": "ready-for-direct-png-dmc-map",
        "target_master_grid": {"width": WIDTH, "height": HEIGHT, "max_long_side_stitches": HEIGHT},
        "target_chart_pages": 4,
        "source_colour_count": COLOURS,
        "dmc_colour_count": None,
    })
    queue_rows.append({
        **common,
        "status": "pending",
        "attempts": 0,
        "last_run": None,
        "last_error": None,
    })

write_json(DESIGNS_PATH, {
    "collection": "iconic-destinations",
    "code_prefix": "D",
    "count": 100,
    "source_policy": "individual-pngs-from-approved-clean-batch-zips-only",
    "metadata_policy": "source-images-manifest-json-is-authoritative",
    "source_manifest": "collections/iconic-destinations/source-images/manifest.json",
    "designs": design_rows,
})

write_json(QUEUE_PATH, {
    "collection": "iconic-destinations",
    "mode": "direct-zip-png-canonical100-v1",
    "active_batch": "canonical-100-D0001-D0100",
    "auto_continue": True,
    "max_attempts_per_design": 3,
    "source_zip": ZIP_REL,
    "source_manifest": "collections/iconic-destinations/source-images/manifest.json",
    "notes": [
        "Canonical collection contains exactly 100 designs, renumbered sequentially D0001-D0100.",
        "Titles and slugs come only from source-images/manifest.json; filenames are never guessed.",
        "Every PNG is exactly 100x120 pixels and exactly 50 source colours.",
        "Each design has its own independent 50-colour source palette.",
    ],
    "items": queue_rows,
})

# Remove historical Iconic product/pattern metadata and rebuild clean skeletons
# for exactly D0001-D0100.
for n in range(1, 151):
    code = f"D{n:04d}-CS"
    for base_dir in (PATTERNS, PRODUCTS):
        p = base_dir / code
        if p.exists():
            shutil.rmtree(p)

for item in items:
    base = item["id"]
    code = f"{base}-CS"
    input_rel = f"collections/iconic-destinations/input-pngs-q50/canonical-100/{item['filename']}"
    write_json(PATTERNS / code / "pattern.json", {
        "code": code,
        "base_design_id": base,
        "technique_code": "CS",
        "collection": "iconic-destinations",
        "palette_mode": "per-design",
        "status": "awaiting-source-artwork",
        "source_asset": input_rel,
        "stitch_width": WIDTH,
        "stitch_height": HEIGHT,
        "total_stitches": 0,
        "threads": [],
        "matrix": [],
    })
    write_json(PRODUCTS / code / "product.json", {
        "code": code,
        "base_design_id": base,
        "technique_code": "CS",
        "collection": "iconic-destinations",
        "title": item["title_en"],
        "title_en": item["title_en"],
        "title_es": item["title_es"],
        "product_title_en": item["product_title_en"],
        "product_title_es": item["product_title_es"],
        "design_slug": item["slug"],
        "technique": "cross-stitch",
        "pattern_file": f"patterns/{code}/pattern.json",
        "template": "cross-stitch.html",
        "website": "www.drielo.com",
        "status": "draft",
        "render_ready": False,
        "renderer": "multitech",
        "source_artwork": input_rel,
        "page_1_asset": None,
        "palette_mode": "per-design",
        "source_manifest": "collections/iconic-destinations/source-images/manifest.json",
    })

# The branch catalog must not retain stale Iconic rows from the previous
# numbering. The publisher will add the new D0001-D0100 rows one by one.
catalog = read_json(CATALOG_PATH)
catalog["products"] = [
    row for row in catalog.get("products", [])
    if row.get("collection") != "iconic-destinations"
]
old_retired = catalog.get("retired_products", [])
catalog["retired_products"] = [
    sku for sku in old_retired
    if not re.fullmatch(r"DRIELO-D\d{4}-CS", str(sku))
]
write_json(CATALOG_PATH, catalog)

# Remove obsolete source ZIPs while keeping collection cover assets and the
# canonical package.
for p in (COL / "assets").glob("*.zip"):
    if p.name != "iconic-destinations-canonical-100.zip":
        p.unlink()

print("ICONIC_CANONICAL_100_PREPARED ids=D0001-D0100 images=100 size=100x120 colours=50")
