<?php get_header(); ?>
<section class="hero"><div class="container"><div class="hero-shell"><div class="hero-copy"><span class="eyebrow"><?php echo esc_html( make_t( 'Patrones digitales para manos inquietas', 'Digital patterns for busy hands' ) ); ?></span><h1><?php echo wp_kses_post( make_t( 'Haz algo que <em>merezca quedarse.</em>', 'Make something <em>worth keeping.</em>' ) ); ?></h1><p><?php echo esc_html( make_t( 'Diseños claros, bonitos y disfrutables. Empezamos por el punto de cruz, pero MAKE está pensado para crecer contigo hacia crochet y nuevas formas de crear.', 'Clear, beautiful patterns designed to be enjoyed. We are starting with cross stitch, but MAKE is built to grow into crochet and whatever you want to make next.' ) ); ?></p><div class="hero-actions"><a class="button button-primary" href="<?php echo esc_url( make_cross_stitch_url() ); ?>"><?php echo esc_html( make_t( 'Ver patrones de punto de cruz', 'Shop cross-stitch patterns' ) ); ?> →</a><button class="button button-secondary" type="button" data-open-overlay="make-search-overlay"><?php echo esc_html( make_t( 'Buscar un diseño', 'Find a design' ) ); ?></button></div><div class="hero-note"><span><i>✓</i><?php echo esc_html( make_t( 'PDF listo para imprimir', 'Print-ready PDF' ) ); ?></span><span><i>✓</i><?php echo esc_html( make_t( 'Paletas verificadas', 'Verified palettes' ) ); ?></span><span><i>✓</i><?php echo esc_html( make_t( 'Descarga inmediata', 'Instant download' ) ); ?></span></div></div><div class="hero-art" aria-hidden="true"><span class="hero-label"><?php echo esc_html( make_t( 'Empieza por aquí ✦', 'Start here ✦' ) ); ?></span><div class="stitch-board"><?php for ( $i = 0; $i < 196; $i++ ) : ?><span></span><?php endfor; ?></div><div class="stitch-hoop"></div></div></div></div></section>

<section class="section"><div class="container"><header class="section-head"><div><span class="section-kicker"><?php echo esc_html( make_t( 'Encuentra tu próximo proyecto', 'Find your next project' ) ); ?></span><h2 class="section-title"><?php echo esc_html( make_t( 'Empieza con lo que te apetece hacer hoy.', 'Start with what you feel like making today.' ) ); ?></h2></div><p class="section-intro"><?php echo esc_html( make_t( 'La estructura está pensada por técnicas y estilos para que sumar crochet, bordado u otras manualidades sea natural.', 'Organized by craft and style, so crochet, embroidery and future crafts can slot in naturally.' ) ); ?></p></header><div class="craft-grid"><a class="craft-card craft-card--feature" href="<?php echo esc_url( make_cross_stitch_url() ); ?>"><small><?php echo esc_html( make_t( 'Disponible ahora', 'Available now' ) ); ?></small><strong><?php echo esc_html( make_t( 'Punto de cruz', 'Cross stitch' ) ); ?></strong><p><?php echo esc_html( make_t( 'Patrones pixel-perfect con paletas limpias y fáciles de seguir.', 'Pixel-perfect patterns with clean, easy-to-follow palettes.' ) ); ?></p></a><a class="craft-card" href="<?php echo esc_url( make_pattern_url( make_t( 'botánico', 'botanical' ) ) ); ?>"><span class="craft-icon">✿</span><small><?php echo esc_html( make_t( 'Colección', 'Collection' ) ); ?></small><strong><?php echo esc_html( make_t( 'Botánicos', 'Botanical' ) ); ?></strong><p><?php echo esc_html( make_t( 'Flores, hojas y diseños orgánicos.', 'Flowers, leaves and organic shapes.' ) ); ?></p></a><a class="craft-card" href="<?php echo esc_url( make_pattern_url( make_t( 'retratos', 'portraits' ) ) ); ?>"><span class="craft-icon">◇</span><small><?php echo esc_html( make_t( 'Colección', 'Collection' ) ); ?></small><strong><?php echo esc_html( make_t( 'Retratos', 'Portraits' ) ); ?></strong><p><?php echo esc_html( make_t( 'Piezas con carácter para enmarcar.', 'Characterful pieces made to frame.' ) ); ?></p></a><div class="craft-card"><span class="craft-icon">⌁</span><small><?php echo esc_html( make_t( 'Próximamente', 'Coming next' ) ); ?></small><strong><?php echo esc_html( make_t( 'Crochet', 'Crochet' ) ); ?></strong><p><?php echo esc_html( make_t( 'MAKE crecerá sin perder su forma.', 'MAKE will grow without losing its shape.' ) ); ?></p></div></div></div></section>

<section class="section products-section"><div class="container"><header class="section-head"><div><span class="section-kicker"><?php echo esc_html( make_t( 'Patrones destacados', 'Featured patterns' ) ); ?></span><h2 class="section-title"><?php echo esc_html( make_t( 'Elige, descarga y empieza.', 'Choose, download, start.' ) ); ?></h2></div><a class="text-link" href="<?php echo esc_url( make_shop_url() ); ?>"><?php echo esc_html( make_t( 'Ver todos', 'See all' ) ); ?> →</a></header><div class="product-grid">
<?php
$products = new WP_Query( array( 'post_type' => 'product', 'post_status' => 'publish', 'posts_per_page' => 4, 'ignore_sticky_posts' => true ) );
if ( $products->have_posts() ) : while ( $products->have_posts() ) : $products->the_post(); $product = function_exists( 'wc_get_product' ) ? wc_get_product( get_the_ID() ) : null; ?>
<article class="product-card"><a href="<?php the_permalink(); ?>"><div class="product-media"><?php if ( has_post_thumbnail() ) { the_post_thumbnail( 'make-card', array( 'loading'=>'lazy','decoding'=>'async' ) ); } else { ?><div class="product-placeholder"><span class="mini-grid"><?php for ( $i=0; $i<64; $i++ ) echo '<i></i>'; ?></span></div><?php } ?><span class="product-badge"><?php echo esc_html( make_t( 'Patrón digital', 'Digital pattern' ) ); ?></span></div><div class="product-copy"><span class="product-type"><?php echo esc_html( make_t( 'Punto de cruz', 'Cross stitch' ) ); ?></span><h3 class="product-title"><?php the_title(); ?></h3><?php if ( $product ) : ?><div class="product-price"><?php echo wp_kses_post( $product->get_price_html() ); ?></div><?php endif; ?></div></a></article>
<?php endwhile; wp_reset_postdata(); else : ?>
<div class="empty-products"><strong><?php echo esc_html( make_t( 'Aquí aparecerán automáticamente tus primeros patrones.', 'Your first patterns will appear here automatically.' ) ); ?></strong><br><small><?php echo esc_html( make_t( 'La home ya está preparada para WooCommerce.', 'The homepage is already WooCommerce-ready.' ) ); ?></small></div>
<?php endif; ?>
</div></div></section>

<section class="section"><div class="container"><div class="promise-grid"><div class="promise-visual" aria-hidden="true"><span class="thread-ball"></span></div><div class="promise-copy"><span class="section-kicker"><?php echo esc_html( make_t( 'La forma de hacer importa', 'How you make matters' ) ); ?></span><h2><?php echo esc_html( make_t( 'Menos ruido. Más ganas de crear.', 'Less noise. More making.' ) ); ?></h2><p><?php echo esc_html( make_t( 'Queremos que cada patrón se sienta cuidado antes incluso de coger la aguja: una imagen clara de lo que vas a hacer, colores coherentes y un PDF que no dé problemas.', 'Every pattern should feel considered before you even pick up a needle: a clear finished preview, coherent colors and a PDF that simply works.' ) ); ?></p><div class="promise-list"><div class="promise-item"><strong><?php echo esc_html( make_t( 'Diseño revisado', 'Checked design' ) ); ?></strong><span><?php echo esc_html( make_t( 'Paleta y gráfico coherentes entre sí.', 'Palette and chart kept in sync.' ) ); ?></span></div><div class="promise-item"><strong><?php echo esc_html( make_t( 'Fácil de imprimir', 'Easy to print' ) ); ?></strong><span><?php echo esc_html( make_t( 'Legible tanto en pantalla como en papel.', 'Readable on screen and on paper.' ) ); ?></span></div><div class="promise-item"><strong><?php echo esc_html( make_t( 'Compra sin fricción', 'Simple purchase' ) ); ?></strong><span><?php echo esc_html( make_t( 'Producto digital listo para descargar.', 'Digital files ready to download.' ) ); ?></span></div><div class="promise-item"><strong><?php echo esc_html( make_t( 'Una marca, muchas técnicas', 'One brand, many crafts' ) ); ?></strong><span><?php echo esc_html( make_t( 'Preparada desde el día uno para crecer.', 'Built from day one to expand.' ) ); ?></span></div></div></div></div></div></section>

<?php $journal = new WP_Query( array( 'post_type'=>'post','post_status'=>'publish','posts_per_page'=>3,'ignore_sticky_posts'=>true ) ); if ( $journal->have_posts() ) : ?>
<section class="section"><div class="container"><header class="section-head"><div><span class="section-kicker"><?php echo esc_html( make_t( 'Cuaderno MAKE', 'MAKE journal' ) ); ?></span><h2 class="section-title"><?php echo esc_html( make_t( 'Ideas para disfrutar más del proceso.', 'Ideas for enjoying the process more.' ) ); ?></h2></div></header><div class="journal-grid"><?php while ( $journal->have_posts() ) : $journal->the_post(); ?><article class="journal-card"><a href="<?php the_permalink(); ?>"><div class="journal-media"><?php if ( has_post_thumbnail() ) the_post_thumbnail( 'make-journal', array( 'loading'=>'lazy','decoding'=>'async' ) ); ?></div><div class="journal-body"><span class="journal-meta"><?php echo esc_html( make_reading_time( get_the_ID() ) ); ?></span><h3 class="journal-title"><?php the_title(); ?></h3><p class="journal-excerpt"><?php echo esc_html( wp_trim_words( get_the_excerpt(), 18 ) ); ?></p></div></a></article><?php endwhile; wp_reset_postdata(); ?></div></div></section>
<?php endif; ?>
<?php get_footer(); ?>
