#!/usr/bin/env python3
"""Generate safe Etsy gallery previews from Drielo product PDFs.

The PDF itself remains the source of truth. We expose useful buying context
(pattern facts, colour key, partial chart samples and print guide) while never
publishing the full colour/symbol overview pages.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import fitz  # PyMuPDF
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1] / "products"
CATALOG = ROOT / "catalog.json"
ASSETS = ROOT / "assets"

# Zero-based PDF pages from the canonical 17-page Drielo pattern template.
# Pages 5 and 6 (full colour/symbol overviews) are deliberately excluded.
PREVIEWS = (
    (1, "finished-design", False),
    (2, "pattern-facts", False),
    (3, "colour-key", False),
    (7, "colour-chart-sample", True),
    (11, "symbol-chart-sample", True),
    (15, "print-guide", False),
)


def safe_code(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_-]+", "-", value).strip("-") or "pattern"


def page_image(page: fitz.Page, partial: bool) -> Image.Image:
    pix = page.get_pixmap(matrix=fitz.Matrix(1.9, 1.9), alpha=False)
    image = Image.frombytes("RGB", (pix.width, pix.height), pix.samples)

    if partial:
        # Show the page heading and only a portion of one enlarged chart.
        # Each source page is already one quarter of the full chart; this crop
        # reduces the visible chart area further so the listing cannot replace
        # the purchased pattern.
        width, height = image.size
        crop_w = max(1, round(width * 0.86))
        crop_h = max(1, round(height * 0.56))
        left = max(0, (width - crop_w) // 2)
        top = max(0, round(height * 0.08))
        image = image.crop((left, top, left + crop_w, min(height, top + crop_h)))

        # Clear, unobtrusive disclosure that this is intentionally partial.
        draw = ImageDraw.Draw(image, "RGBA")
        label = "PREVIEW · PARTIAL CHART"
        font = ImageFont.load_default()
        box = draw.textbbox((0, 0), label, font=font)
        pad = max(8, image.width // 140)
        bw = box[2] - box[0] + pad * 2
        bh = box[3] - box[1] + pad * 2
        x = max(pad, image.width - bw - pad)
        y = max(pad, image.height - bh - pad)
        draw.rounded_rectangle((x, y, x + bw, y + bh), radius=pad, fill=(255, 255, 255, 225))
        draw.text((x + pad, y + pad), label, font=font, fill=(35, 20, 30, 255))

    image.thumbnail((1600, 2000), Image.Resampling.LANCZOS)
    return image


def main() -> None:
    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    products = data.get("products", [])
    ASSETS.mkdir(parents=True, exist_ok=True)

    generated_total = 0
    changed = False

    for row in products:
        code = safe_code(str(row.get("code", "")))
        download = str(row.get("download", "")).strip()
        if not download:
            continue

        pdf = ROOT / download
        if not pdf.is_file() or pdf.suffix.lower() != ".pdf":
            continue

        try:
            document = fitz.open(pdf)
        except Exception as exc:
            print(f"WARNING {code}: cannot open {download}: {exc}")
            continue

        generated = []
        try:
            for page_index, slug, partial in PREVIEWS:
                if page_index >= document.page_count:
                    continue
                try:
                    image = page_image(document.load_page(page_index), partial)
                    filename = f"{code}-etsy-{slug}.webp"
                    target = ASSETS / filename
                    image.save(target, "WEBP", quality=84, method=6)
                    if target.stat().st_size < 8_000:
                        target.unlink(missing_ok=True)
                        continue
                    generated.append(f"assets/{filename}")
                except Exception as exc:
                    print(f"WARNING {code}: preview {slug} failed: {exc}")
        finally:
            document.close()

        if not generated:
            continue

        # Preserve any manually curated gallery images and replace only previews
        # generated by this script.
        old_gallery = [str(x) for x in row.get("gallery", [])]
        manual = [x for x in old_gallery if f"{code}-etsy-" not in Path(x).name]
        new_gallery = manual + generated
        if new_gallery != old_gallery:
            row["gallery"] = new_gallery
            changed = True

        generated_total += len(generated)
        print(f"{code}: generated {len(generated)} Etsy previews")

    if changed:
        CATALOG.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"Generated {generated_total} Etsy preview images")


if __name__ == "__main__":
    main()
